### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [babel/babel-sublime-snippets#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by sebmck** [comment]
Good thing there's no code :) Please stop spamming GitHub.

**Comment by karan** [comment]
What spam?

**Comment by sebmck** [comment]
@karan oiax/capejs#6 pjotrp/guix-notes#2 topherhunt/vanilla_app#1 Masterzach32/SideScrollerGame#2 simon-qi/Personal-website#1 sjmcpherso/Front-End-Developer-Learnings#1 and more. You've literally setup a bot that open issues on repos which [GitHub is against](http://www.wired.com/2012/12/github-bots/).

**Comment by karan** [comment]
Says wired, from 2012.. It's a bot, but it's highly controlled at this point, I check every issue manually and respond to them manually. It's all in good vein, really.

**Comment by thejameskyle** [comment]
It's inappropriate and you should stop immediately. There are perfectly valid reasons not to have a license in a repository and not having any code is one of them.

**Comment by thejameskyle** [comment]
Also, reported to GitHub.
