### ISSUE TITLE
Support React 15.5 PropTypes

### ISSUE THREAD

**Issue by MilllerTime** [babel/babel-sublime-snippets#26]
New in [React 15.5](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) is a breaking change where `PropTypes` are no longer included within React, and have instead been moved to a separate prop-types package. Dropping the `React.` prefix from the PropTypes snippets should do it.

**Comment by brownieboy** [comment]
Fixed as part of 1.0.7, which is now live on Package Manager.

**Comment by MilllerTime** [comment]
Excellent, thanks!
