### ISSUE TITLE
how to use wrap in a component?

### ISSUE THREAD

**Issue by deezahyn** [babel/babel-sublime-snippets#3]
I try to wrap this in a react component:
```
<div>hello world</div>
```

I get this:

```
<div>hello <Component>
<div>hello   world</div>
<div>hello </Component>
```

I'm pretty sure that's not the intended output right?

**Comment by zertosh** [comment]
Sorry about that - there was a bug where it didn't handle single line selections without leading whitespace. I published the fix v1.0.2 - it'll take about an hour for Package Control to pick up the update.

**Comment by zertosh** [comment]
Err. Correction, with and without leading whitespace, it's just that the brokeness looked different.

**Comment by deezahyn** [comment]
thanks that was fast! @zertosh
