### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by brownieboy** [babel/babel-sublime-snippets#31]
Last update to the Master branch was 18 months ago.   No other branches in the repository.  No movement visible on important issues, e.g. #28 .

So has this package been abandoned now?

**Comment by xtuc** [comment]
This project is looking for maintainers! Do you want to contribute?

**Comment by brownieboy** [comment]
Sure, although I've never programmed in Python before!

I think I can managed a PR to fix #28, at least.

**Comment by brownieboy** [comment]
And we are up and running again!  #28 now fixed and rolled out as version 1.0.7.

Many thanks to @xtuc for picking up the ball here.
