### ISSUE TITLE
question: How to assign keybinding?

### ISSUE THREAD

**Issue by deezahyn** [babel/babel-sublime-snippets#4]
I'm on a mac, using the default keybinding:

```
{
    "keys": ["ctrl+shift+,"],
    "command": "insert_snippet",
    "args": {
      "name": "Packages/Babel Sublime Snippets/react_wrap.sublime-snippet"
    }
  }
```

I highlight a jsx and try to press ctrl+shift+, and nothing happens, tried using different combination as well, super+shift+m for example.

Not sure if this is an ST3 bug but any help is much appreciated.

**Comment by zertosh** [comment]
Sorry again @deezahyn. The README just had the wrong directory - that should fix it. Reaching it via the Command Palette should've still worked.

Fun fact: The development directory is not the same as the install directory. I kinda never checked what directory it would actually install to.

**Comment by deezahyn** [comment]
works! I kinda missed that as well lol, thank you for the fast fix.
